version: 2
jobs:
  install:
    docker:
      - image: circleci/node:8.9.4
    steps:
      - checkout
      - restore_cache:
          key: dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Install
          command: test -d ./node_modules || npm install
      - save_cache:
          paths:
            - ./node_modules
          key: dependencies-{{ checksum "package-lock.json" }}
      - persist_to_workspace:
          root: .
          paths:
            - .
  test:
    docker:
      - image: circleci/node:8.9.4
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Test
          command: npm test
workflows:
  version: 2
  install-and-test:
    jobs:
      - install
      - test:
          requires:
            - install
